//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int stockId { get; set; }
        public string stockName { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> quantity_remaining { get; set; }
        public Nullable<int> addedBy { get; set; }
        public string status { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
